Bump the major-dependencies group across 1 directory with 4 updates (#875)
* Bump the major-dependencies group across 1 directory with 4 updates

Bumps the major-dependencies group with 4 updates in the / directory: [@navikt/ds-css](https://github.com/navikt/aksel), [@navikt/ds-react](https://github.com/navikt/aksel), [@navikt/nav-dekoratoren-moduler](https://github.com/navikt/nav-dekoratoren-moduler) and [date-fns](https://github.com/date-fns/date-fns).


Updates `@navikt/ds-css` from 6.16.3 to 7.0.1
- [Release notes](https://github.com/navikt/aksel/releases)
- [Changelog](https://github.com/navikt/aksel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/navikt/aksel/compare/@navikt/ds-css@6.16.3...@navikt/ds-css@7.0.1)

Updates `@navikt/ds-react` from 6.16.3 to 7.0.1
- [Release notes](https://github.com/navikt/aksel/releases)
- [Changelog](https://github.com/navikt/aksel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/navikt/aksel/compare/@navikt/ds-react@6.16.3...@navikt/ds-react@7.0.1)

Updates `@navikt/nav-dekoratoren-moduler` from 2.1.6 to 3.1.0
- [Release notes](https://github.com/navikt/nav-dekoratoren-moduler/releases)
- [Commits](https://github.com/navikt/nav-dekoratoren-moduler/compare/v2.1.6...v3.1.0)

Updates `date-fns` from 3.6.0 to 4.1.0
- [Release notes](https://github.com/date-fns/date-fns/releases)
- [Changelog](https://github.com/date-fns/date-fns/blob/main/CHANGELOG.md)
- [Commits](https://github.com/date-fns/date-fns/compare/v3.6.0...v4.1.0)

---
updated-dependencies:
- dependency-name: "@navikt/ds-css"
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: major-dependencies
- dependency-name: "@navikt/ds-react"
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: major-dependencies
- dependency-name: "@navikt/nav-dekoratoren-moduler"
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: major-dependencies
- dependency-name: date-fns
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: major-dependencies
...

Signed-off-by: dependabot[bot] <support@github.com>

* Slettet node_modules og yarn.lock - kjørt npm install -D csp-header og uninstall på csp-header - fordi jeg fikk error 'Error: Cannot find module 'csp-header'
'. Lagt til align-content: center på Filvelger slik at tekst ligger i senter av boksen.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: gunnsteingarmo <gunnstein.hoj.garmo@nav.no>